# Generated by Django 5.2.7 on 2025-11-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_profile_email_alter_profile_gender_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
