# Generated by Django 5.2.7 on 2025-11-26 07:24

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[userauths.models.validate_iium_email]),
        ),
    ]
