# Generated by Django 5.2.7 on 2025-12-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_rentalitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='title',
            new_name='item',
        ),
    ]
