# Generated by Django 5.2.7 on 2025-12-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='RentalItem',
        ),
    ]
