# Generated by Django 5.2.7 on 2025-12-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_grouppost_page_pagepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='page',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('General', 'General'), ('Open for Rent', 'Open for Rent'), ('Looking to Rent', 'Looking to Rent')], default='General', max_length=100),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupPost',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PagePost',
        ),
    ]
