# Generated by Django 5.2.7 on 2025-12-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
            ],
            options={
                'verbose_name': 'Saved Post',
                'verbose_name_plural': 'Saved Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.post',),
        ),
    ]
