# Generated by Django 5.2.7 on 2025-12-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_image_postthumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='page',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='postthumbnail',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupPost',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PagePost',
        ),
    ]
