# Generated by Django 5.2.7 on 2025-12-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Only Me', 'Only Me'), ('Everyone', 'Everyone'), ('General', 'General'), ('Open for Rent', 'Open for Rent'), ('Looking to Rent', 'Looking to Rent')], default='General', max_length=100),
        ),
    ]
