# Generated by Django 5.2.7 on 2025-12-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_notification_notification_type_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Like', 'New Like'), ('New Follower', 'New Follower'), ('New Comment', 'New Comment'), ('Comment Liked', 'Comment Liked'), ('Comment Replied', 'Comment Replied'), ('Friend Request', 'Friend Request'), ('Friend Accepted', 'Friend Accepted'), ('Dispute Report', 'Dispute Report'), ('Dispute Status Update', 'Dispute Status Update')], max_length=100),
        ),
    ]
