# Generated by Django 5.2.7 on 2025-12-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_disputereport_reported_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('General', 'General'), ('Open for Rent', 'Open for Rent'), ('Looking to Rent', 'Looking to Rent')], default='General', max_length=100),
        ),
    ]
