# Generated by Django 5.2 on 2025-12-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_post_visibility'),
        ('core', '0019_rentalrequest_handed_over_rentalrequest_returned_and_more'),
    ]

    operations = [
    ]
