# Generated by Django 5.2.7 on 2025-12-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20251230_1547'),
        ('core', '0022_alter_notification_notification_type'),
    ]

    operations = [
    ]
