# Generated by Django 5.2.7 on 2025-12-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20251230_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Like', 'New Like'), ('New Follower', 'New Follower'), ('New Comment', 'New Comment'), ('Comment Liked', 'Comment Liked'), ('Comment Replied', 'Comment Replied'), ('Friend Request', 'Friend Request'), ('Friend Accepted', 'Friend Accepted'), ('Dispute Report', 'Dispute Report'), ('Dispute Status Update', 'Dispute Status Update'), ('Rental Request', 'Rental Request'), ('Rental Request Approved', 'Rental Request Approved'), ('Rental Request Declined', 'Rental Request Declined'), ('Item Handed Over', 'Item Handed Over'), ('Rental Request Cancelled', 'Rental Request Cancelled'), ('Payment Completed', 'Payment Completed'), ('Rental Period Ended', 'Rental Period Ended'), ('Rental Completed', 'Rental Completed')], max_length=100),
        ),
    ]
