# Generated by Django 5.2.7 on 2025-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_notification_notification_type'),
        ('core', '0024_post_product'),
    ]

    operations = [
    ]
