# Generated by Django 5.2.7 on 2025-12-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
    ]
