# Generated by Django 5.2.7 on 2026-01-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('rental_card', 'Rental Card')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rental_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='core.rentalrequest'),
        ),
    ]
