# Generated by Django 5.2 on 2026-01-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Like', 'New Like'), ('New Follower', 'New Follower'), ('New Comment', 'New Comment'), ('Comment Liked', 'Comment Liked'), ('Comment Replied', 'Comment Replied'), ('Friend Request', 'Friend Request'), ('Friend Accepted', 'Friend Accepted'), ('Friend Request Accepted By Me', 'Friend Request Accepted By Me'), ('Friend Request Declined By Me', 'Friend Request Declined By Me'), ('Dispute Report', 'Dispute Report'), ('Dispute Status Update', 'Dispute Status Update'), ('Rental Request', 'Rental Request'), ('Rental Request Approved', 'Rental Request Approved'), ('Rental Request Declined', 'Rental Request Declined'), ('Item Handed Over', 'Item Handed Over'), ('Item Received', 'Item Received'), ('Item Returned', 'Item Returned'), ('Rental Request Cancelled', 'Rental Request Cancelled'), ('Payment Completed', 'Payment Completed'), ('Rental Period Ended', 'Rental Period Ended'), ('Rental Completed', 'Rental Completed')], max_length=100),
        ),
    ]
