# Generated by Django 5.2 on 2026-01-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Unfriend', 'Unfriend')], default='Pending', max_length=100),
        ),
    ]
