# Generated by Django 5.2 on 2026-01-02 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_friendrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Like', 'New Like'), ('New Follower', 'New Follower'), ('New Comment', 'New Comment'), ('Comment Liked', 'Comment Liked'), ('Comment Replied', 'Comment Replied'), ('Friend Added', 'Friend Added'), ('Dispute Report', 'Dispute Report'), ('Dispute Status Update', 'Dispute Status Update'), ('Rental Request', 'Rental Request'), ('Rental Request Approved', 'Rental Request Approved'), ('Rental Request Declined', 'Rental Request Declined'), ('Item Handed Over', 'Item Handed Over'), ('Item Received', 'Item Received'), ('Item Returned', 'Item Returned'), ('Rental Request Cancelled', 'Rental Request Cancelled'), ('Payment Completed', 'Payment Completed'), ('Rental Period Ended', 'Rental Period Ended'), ('Rental Completed', 'Rental Completed')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user', 'friend')},
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
