# Generated by Django 5.2.7 on 2026-01-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_friend_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
