"""
Django settings for fyp_proj project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--1#6m35&b_41&*_d-_@pewz6-s)rvbuck_tmr_&oh2n(872_2u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '172.20.10.3'] #ikut host server sendiri



# Application definition

INSTALLED_APPS = [
    #custom django admin
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #email verification link
    'django.contrib.sites',

    #3rd party App
    'crispy_forms',
    'taggit',
    'import_export', #help import & export model files
    
    #custom app
    'userauths',
    'core', #dah remove rental app
   
]

#required by django.contrib.sites
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fyp_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], #create folder templates (connect)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'core.context_processors.notification_context', #tambah context processor
            ],
        },
    },
]

WSGI_APPLICATION = 'fyp_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/' #grab static file
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles") #static folder ada css, js, img
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")] #configure static files

MEDIA_URL = '/media/' #grab media file
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'userauths.User' #'folder.whatmodelyouwannacall'

LOGIN_REDIRECT_URL = 'core:feed'
LOGOUT = 'userauths:sign-up'
LOGIN_URL = 'userauths:sign-up'  #if user tk login, redirect to sign-up page

#email config (gmail stmp)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'hnllee90@gmail.com'
EMAIL_HOST_PASSWORD = 'asifvtygtnrorvui'
DEFAULT_FROM_EMAIL = 'RentAll <noreply@gmail.com'

JAZZMIN_SETTINGS = {
    'site_header': "Rent All",
    'site_brand': "Admin", #tukar nama kat bahagian atas kiri
    'site_logo': "assets/images/logo_admin.png", #logo baru
    'copyright':  "All Right Reserved 2023",
    "welcome_sign": "Welcome to Rent All Admin, Login Now.",
    "topmenu_links": [
        #{"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        #{"name": "Company", "url": "/admin/addons/company/"},
        #{"name": "Users", "url": "/admin/userauths/user/"},
    ],

    "order_with_respect_to": [
        "core",
        "userauths",
        "addon", 
        "core.post",
        "core.friend",
        "core.FriendRequest",
        #"userauths",
        #"addon",
    ],
    
    "icons": {
        "admin.LogEntry": "fas fa-file",

        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",

        "userauths.User": "fas fa-user",
        "userauths.Profile":"fas fa-address-card",

        #"core.post": "fas fa-th",
        #"core.Page": "fas fa-users",
        #"core.ReplyComment": "fas fa-reply",
        #"core.group": "fas fa-layer-group",
        #"core.notification": "fas fa-bell",
        #"core.Comment":"fas fa-comments",
        #"core.Friend":"fas fa-users",
        #"core.FriendRequest":"fas fa-user-plus",
    },

    "show_ui_builder" : True
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-olive",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cyborg",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
